### ISSUE TITLE
Any interest in dusting this off?

### ISSUE THREAD

**Issue by kyprifog** [da-x/alacritmux#4]
I was wondering if you had any interest in dusting this off?  I am needing different size fonts in different tmux windows (and possibly panes), and this seems like the only solution out there?   Unfortunately the repo has suffered some bit-rot and I can't get it to build.

**Comment by kyprifog** [comment]
Nvmind i found a workaround using xdotool

**Comment by lorenoamori** [comment]
@kyprifog might you be so kind as to share it with us?
